User authorization
OpenRbt/lea-central-wash pull request #32
Opened 2021-02-03 07:43 UTC by kosetin

Secured /status-collection and /save-collection with database based user authorization

2021-02-03 09:03 UTC, DiaElectronics commented on cmd/storage/internal/app/app.go
> +	"github.com/DiaElectronics/lea-central-wash/storageapi"
сразу нет. 
app никогда ничего ни при каких обстоятельствах не импортирует.
Все стальные модули должны использовать модели определенные в app

2021-02-07 10:49 UTC, DiaElectronics requested changes

2021-02-07 10:49 UTC, DiaElectronics commented on cmd/storage/internal/app/storage.go
> +	user, errOldUser := a.repo.User(userData.Login)
Почему не по ID пользователя?

2021-02-07 10:49 UTC, DiaElectronics commented on cmd/storage/internal/app/storage.go
> +	if userData.FirstName != "" {
"" - это тоже значение на которое можно изменить поле.
Если надо изменять, только отправленные поля:
1. В swagger добавляешь к полю x-nullable: true.
2. В апи у тебя поле становится ссылкой, если поле не указано в json, оно будет nil.
3. При обновлении if userData.FirstName != nil {

2021-02-07 10:49 UTC, DiaElectronics commented on cmd/storage/internal/app/storage.go
> +	if userData.Password != "" {
Изменять пароль в методе обновления пользователя нельзя. Нужен отдельный метод.
В нем надо требовать передать текущий пароль и проверить, совпадает он или нет.
Для админа отдельный метод.

2021-02-07 10:49 UTC, DiaElectronics commented on cmd/storage/internal/app/storage.go
> +	errRepo := a.repo.DeleteUser(login)
Почему не по ID пользователя?

2021-02-07 10:49 UTC, DiaElectronics commented on cmd/storage/internal/auth/auth.go
> +		user, err := a.app.GetUserByToken(context.Background(), a.log, token)
Это было для примера, тут это лишнее.

2021-02-07 10:49 UTC, DiaElectronics commented on cmd/storage/internal/dal/dal.go
> +		err := tx.NamedSelectContext(ctx, &res, sqlGetUser, argGetUser{
NamedGetContext

2021-02-07 10:49 UTC, DiaElectronics commented on cmd/storage/internal/dal/dal.go
> +		if err != nil {
switch {
		case errors.Is(err, sql.ErrNoRows):
			return app.ErrNotFound
		case err != nil:
			return err
		}

2021-02-07 10:49 UTC, DiaElectronics commented on cmd/storage/internal/dal/dal.go
> +		user = users[0]
А если не найдет пользователей?

2021-02-07 10:49 UTC, DiaElectronics commented on cmd/storage/internal/dal/dal.go
> +			Password:   userData.Password,
это тут лишнее

2021-02-07 10:49 UTC, DiaElectronics commented on cmd/storage/internal/dal/sql.go
> +WHERE login = :login
лучше так не сравнивать строки.
WHERE lower(login) = lower(:login)

2021-02-07 10:49 UTC, DiaElectronics commented on cmd/storage/internal/extapi/handlers.go
> +	return op.NewGetUserNoContent()
Для чего этот метод?

2021-02-07 10:49 UTC, DiaElectronics commented on cmd/storage/internal/extapi/handlers.go
> +	if err != nil {
Почему BadRequest?
Разве тут не могут быть разные ошибки?

2021-02-07 10:49 UTC, DiaElectronics commented on cmd/storage/internal/migration/00011_add-users.sql
> +login       TEXT NOT NULL UNIQUE,
По этому условию admin и Admin - разные пользователи.
Лучше его убрать, меньше ошибок надо будет обрабатывать.
И добавить уникальный индекс.
CREATE UNIQUE INDEX users_unique_lower_login_idx ON users (LOWER(login));

2021-02-07 10:49 UTC, DiaElectronics commented on cmd/storage/internal/migration/00011_add-users.sql
> +CREATE TABLE users (
В проекте названия таблиц в единственном числе

2021-02-07 10:49 UTC, DiaElectronics commented on storageapi/swagger.yml
> +            type: object
лишнее

2021-02-07 16:26 UTC, kosetin commented on cmd/storage/internal/extapi/handlers.go
> +	return op.NewGetUserNoContent()
Для проверки, зарегистрирован ли пользователь с данным паролем или нет. Вызывается при входе в приложение оператора (самая первая картинка, где пин вводится)

2021-02-07 16:35 UTC, kosetin commented on cmd/storage/internal/migration/00011_add-users.sql
> +CREATE TABLE users (
Singular "user" is a reserved keyword

2021-02-10 08:11 UTC, DiaElectronics requested changes

2021-02-10 11:40 UTC, kosetin commented on cmd/storage/internal/dal/dal.go
> +		return err
Не получилось заставить NamedExec возвращать какую-нибудь ошибку типа sql.ErrNoRows, если пользователь с данным логином не был найден. Как это сделать?

2021-02-10 11:46 UTC, kosetin commented on storageapi/swagger.yml
> +        - isEngineer
Если нет отчества - пустую строку? Можно сделать отчество x-nullable? Но права доступа нужны, иначе юзер будет по умолчанию false, false, false и нужно будет слать второй запрос PUT, чтобы задать права доступа - не очень удобно и клиент будет должен об этом вспомнить.

2021-02-10 11:46 UTC, kosetin commented on storageapi/swagger.yml
> +                maxLength: 4
В ТЗ нет

2021-02-10 11:57 UTC, kosetin commented on cmd/storage/internal/app/app.go
> +	ErrConstraintViolation = errors.New("constraint violation")
сделал

2021-02-10 12:04 UTC, DiaElectronics commented on storageapi/swagger.yml
> +        - isEngineer
Просто не обязательные сделай. на входе получишь значение "". x-nullable не надо. 
Также и с правами.
Из обязательных тут логин и пароль.

2021-02-10 12:06 UTC, DiaElectronics commented on cmd/storage/internal/dal/dal.go
> +		return err
Ошибка в другом, если пользователь, что то добавлял, то на него есть ссылки и удалить его не получится

2021-02-13 12:51 UTC, merged